"""baseline schema

Revision ID: 3c61ddde32ef
Revises: 
Create Date: 2026-08-27 07:56:53.815810+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c61ddde32ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_name', sa.String(length=512), nullable=True),
    sa.Column('case_id', sa.String(length=255), nullable=True),
    sa.Column('case_title', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_case_id', ['case_id'], unique=False)
        batch_op.create_index('ix_audit_resource_type', ['resource_type'], unique=False)
        batch_op.create_index('ix_audit_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_username', ['username'], unique=False)

    op.create_table('client_doc_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slots', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('playbooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', sa.Text(), nullable=True),
    sa.Column('edges', sa.Text(), nullable=True),
    sa.Column('layout_dir', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_doc_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('tags_detected', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'owner', 'analyst', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vaults',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('doc_template_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_template_id'], ['client_doc_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', 'archived', name='casestatus'), nullable=False),
    sa.Column('severity', sa.Enum('informational', 'low', 'medium', 'high', 'critical', name='caseseverity'), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('tlp', sa.String(length=10), nullable=True),
    sa.Column('case_type', sa.Enum('ir', 'ctf', 'pentest', 'sample', name='casetype'), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('quick_notes', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('report_analysis', sa.Text(), nullable=True),
    sa.Column('report_remediation', sa.Text(), nullable=True),
    sa.Column('report_conclusion', sa.Text(), nullable=True),
    sa.Column('report_sections_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('slot', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('workstation', 'server', 'domain_controller', 'network_device', 'firewall', 'vpn', 'application', 'database', 'user_account', 'service_account', 'cloud_resource', 'container', 'mobile', 'printer', 'iot', 'other', name='assettype'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('compromised', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_graphs',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('binary_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('enc_path', sa.Text(), nullable=False),
    sa.Column('salt_hex', sa.String(length=64), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('binary_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('analysed_at', sa.DateTime(), nullable=True),
    sa.Column('added_to_evidence', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('binary_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_binary_files_case_id'), ['case_id'], unique=False)

    op.create_table('case_playbooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('playbook_id', sa.String(), nullable=False),
    sa.Column('step_states', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_ttps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('technique_id', sa.String(length=32), nullable=False),
    sa.Column('technique_name', sa.String(length=512), nullable=True),
    sa.Column('tactic', sa.String(length=128), nullable=True),
    sa.Column('tactic_name', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'technique_id', 'tactic', name='uq_case_ttp')
    )
    with op.batch_alter_table('case_ttps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_ttps_case_id'), ['case_id'], unique=False)

    op.create_table('chainsaw_case_selections',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('alert_ids', sa.JSON(), nullable=False),
    sa.Column('sent_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('email_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('evidence_type', sa.Enum('malware', 'artifact', 'log', 'memory_dump', 'disk_image', 'network_capture', 'document', 'report', 'other', name='evidencetype'), nullable=False),
    sa.Column('source_location', sa.Text(), nullable=True),
    sa.Column('acquisition_method', sa.Enum('manual', 'forensic_copy', 'live_acquisition', 'logical_copy', 'remote_collection', 'other', name='acquisitionmethod'), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('collected_by', sa.String(length=255), nullable=True),
    sa.Column('chain_of_custody', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evtx_case_selections',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('sent_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('evtx_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('added_to_evidence', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evtx_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evtx_files_case_id'), ['case_id'], unique=False)

    op.create_table('imported_collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('processed_files', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_collections_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_collections_session_id'), ['session_id'], unique=False)

    op.create_table('iocs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ip', 'domain', 'url', 'asn', 'hash_md5', 'hash_sha1', 'hash_sha256', 'filename', 'certificate', 'email', 'email_subject', 'sender_name', 'registry', 'user_agent', 'phone', 'other', name='ioctype'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='iocconfidence'), nullable=True),
    sa.Column('tlp', sa.String(length=20), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_dumps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('os_type', sa.String(length=16), nullable=False),
    sa.Column('symbols_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_dumps', schema=None) as batch_op:
        batch_op.create_index('ix_memory_dump_case_id', ['case_id'], unique=False)

    op.create_table('report_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.create_index('ix_report_versions_case', ['case_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_ts', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('raw_source', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chainsaw_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['evtx_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chainsaw_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chainsaw_scans_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chainsaw_scans_file_id'), ['file_id'], unique=False)

    op.create_table('csv_artifact_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('columns', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('date_column', sa.String(length=200), nullable=True),
    sa.Column('ez_label', sa.String(length=100), nullable=True),
    sa.Column('ez_category', sa.String(length=100), nullable=True),
    sa.Column('source_timezone', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evtx_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('level_name', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=512), nullable=True),
    sa.Column('computer', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('searchable_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['evtx_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evtx_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evtx_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index('ix_evtx_events_file_channel', ['file_id', 'channel'], unique=False)
        batch_op.create_index('ix_evtx_events_file_eid', ['file_id', 'event_id'], unique=False)
        batch_op.create_index('ix_evtx_events_file_level', ['file_id', 'level'], unique=False)
        batch_op.create_index('ix_evtx_events_file_time', ['file_id', 'time_created'], unique=False)

    op.create_table('imported_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_label', sa.String(), nullable=True),
    sa.Column('destination_page', sa.String(), nullable=True),
    sa.Column('destination_label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('csv_artifact_id', sa.String(), nullable=True),
    sa.Column('added_to_evidence', sa.Boolean(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['imported_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_files_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_files_collection_id'), ['collection_id'], unique=False)

    op.create_table('incident_log_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('timeline_event_id', sa.String(), nullable=True),
    sa.Column('event_ts', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_plugin_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dump_id', sa.String(), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('plugin_args', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dump_id'], ['memory_dumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_plugin_results', schema=None) as batch_op:
        batch_op.create_index('ix_mem_plugin_dump_id', ['dump_id'], unique=False)
        batch_op.create_index('ix_mem_plugin_is_custom', ['is_custom'], unique=False)
        batch_op.create_index('ix_mem_plugin_name', ['plugin_name'], unique=False)

    op.create_table('amcache_file_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('application_name', sa.Text(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('file_key_last_write', sa.DateTime(), nullable=True),
    sa.Column('sha1', sa.String(), nullable=True),
    sa.Column('is_os_component', sa.Boolean(), nullable=True),
    sa.Column('full_path', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.Column('link_date', sa.DateTime(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_pe_file', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amcache_file_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amcache_file_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amcache_file_entries_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amcache_file_entries_sha1'), ['sha1'], unique=False)

    op.create_table('amcache_program_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('key_last_write', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('root_dir_path', sa.Text(), nullable=True),
    sa.Column('uninstall_string', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amcache_program_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amcache_program_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amcache_program_entries_file_id'), ['file_id'], unique=False)

    op.create_table('chainsaw_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(length=512), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('sigma_status', sa.String(length=32), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('computer', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=512), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('added_to_timeline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['evtx_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['chainsaw_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chainsaw_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chainsaw_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_chainsaw_alerts_case_level', ['case_id', 'level'], unique=False)
        batch_op.create_index('ix_chainsaw_alerts_case_ts', ['case_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_chainsaw_alerts_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_chainsaw_alerts_rule_name'), ['rule_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chainsaw_alerts_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index('ix_chainsaw_alerts_scan_level', ['scan_id', 'level'], unique=False)
        batch_op.create_index(batch_op.f('ix_chainsaw_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('jumplist_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('jl_type', sa.String(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('app_description', sa.Text(), nullable=True),
    sa.Column('mru', sa.Integer(), nullable=True),
    sa.Column('entry_number', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('pin_status', sa.String(), nullable=True),
    sa.Column('target_created', sa.DateTime(), nullable=True),
    sa.Column('target_modified', sa.DateTime(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('target_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('drive_type', sa.String(), nullable=True),
    sa.Column('volume_serial', sa.String(), nullable=True),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jumplist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jumplist_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jumplist_entries_file_id'), ['file_id'], unique=False)

    op.create_table('lnk_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_created', sa.DateTime(), nullable=True),
    sa.Column('source_modified', sa.DateTime(), nullable=True),
    sa.Column('source_accessed', sa.DateTime(), nullable=True),
    sa.Column('target_created', sa.DateTime(), nullable=True),
    sa.Column('target_modified', sa.DateTime(), nullable=True),
    sa.Column('target_accessed', sa.DateTime(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('network_path', sa.Text(), nullable=True),
    sa.Column('common_path', sa.Text(), nullable=True),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('target_path', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('drive_type', sa.String(), nullable=True),
    sa.Column('volume_serial', sa.String(), nullable=True),
    sa.Column('volume_label', sa.String(), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('working_dir', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lnk_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lnk_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lnk_entries_file_id'), ['file_id'], unique=False)

    op.create_table('recycle_bin_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recycle_bin_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recycle_bin_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycle_bin_entries_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycle_bin_entries_sid'), ['sid'], unique=False)

    op.create_table('registry_batch_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('hive_path', sa.Text(), nullable=True),
    sa.Column('hive_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('key_path', sa.Text(), nullable=True),
    sa.Column('value_name', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('value_data', sa.Text(), nullable=True),
    sa.Column('value_data2', sa.Text(), nullable=True),
    sa.Column('value_data3', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('last_write_timestamp', sa.DateTime(), nullable=True),
    sa.Column('plugin_detail_file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registry_batch_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registry_batch_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registry_batch_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_registry_batch_entries_file_id'), ['file_id'], unique=False)

    op.create_table('shellbag_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('bag_path', sa.String(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('mru_position', sa.Integer(), nullable=True),
    sa.Column('absolute_path', sa.Text(), nullable=True),
    sa.Column('shell_type', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('accessed_on', sa.DateTime(), nullable=True),
    sa.Column('last_write_time', sa.DateTime(), nullable=True),
    sa.Column('first_interacted', sa.DateTime(), nullable=True),
    sa.Column('last_interacted', sa.DateTime(), nullable=True),
    sa.Column('has_explored', sa.Boolean(), nullable=True),
    sa.Column('hive_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shellbag_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shellbag_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shellbag_entries_file_id'), ['file_id'], unique=False)

    op.create_table('shimcache_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('control_set', sa.Integer(), nullable=True),
    sa.Column('cache_position', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('executed', sa.String(), nullable=True),
    sa.Column('duplicate', sa.Boolean(), nullable=True),
    sa.Column('source_hive', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shimcache_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shimcache_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shimcache_entries_file_id'), ['file_id'], unique=False)

    op.create_table('srum_app_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('exe_info', sa.Text(), nullable=True),
    sa.Column('exe_description', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('bg_bytes_read', sa.BigInteger(), nullable=True),
    sa.Column('bg_bytes_written', sa.BigInteger(), nullable=True),
    sa.Column('fg_bytes_read', sa.BigInteger(), nullable=True),
    sa.Column('fg_bytes_written', sa.BigInteger(), nullable=True),
    sa.Column('face_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('srum_app_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_srum_app_usage_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_srum_app_usage_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_srum_app_usage_timestamp'), ['timestamp'], unique=False)

    op.create_table('srum_network_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('exe_info', sa.Text(), nullable=True),
    sa.Column('exe_description', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('bytes_received', sa.BigInteger(), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('profile_name', sa.Text(), nullable=True),
    sa.Column('interface_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('srum_network_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_srum_network_usage_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_srum_network_usage_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_srum_network_usage_timestamp'), ['timestamp'], unique=False)

    op.create_table('windows_timeline_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('executable', sa.Text(), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('content_info', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['imported_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('windows_timeline_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_windows_timeline_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_windows_timeline_entries_file_id'), ['file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('windows_timeline_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_windows_timeline_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_windows_timeline_entries_case_id'))

    op.drop_table('windows_timeline_entries')
    with op.batch_alter_table('srum_network_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srum_network_usage_timestamp'))
        batch_op.drop_index(batch_op.f('ix_srum_network_usage_file_id'))
        batch_op.drop_index(batch_op.f('ix_srum_network_usage_case_id'))

    op.drop_table('srum_network_usage')
    with op.batch_alter_table('srum_app_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srum_app_usage_timestamp'))
        batch_op.drop_index(batch_op.f('ix_srum_app_usage_file_id'))
        batch_op.drop_index(batch_op.f('ix_srum_app_usage_case_id'))

    op.drop_table('srum_app_usage')
    with op.batch_alter_table('shimcache_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shimcache_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_shimcache_entries_case_id'))

    op.drop_table('shimcache_entries')
    with op.batch_alter_table('shellbag_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shellbag_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_shellbag_entries_case_id'))

    op.drop_table('shellbag_entries')
    with op.batch_alter_table('registry_batch_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registry_batch_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_registry_batch_entries_category'))
        batch_op.drop_index(batch_op.f('ix_registry_batch_entries_case_id'))

    op.drop_table('registry_batch_entries')
    with op.batch_alter_table('recycle_bin_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recycle_bin_entries_sid'))
        batch_op.drop_index(batch_op.f('ix_recycle_bin_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_recycle_bin_entries_case_id'))

    op.drop_table('recycle_bin_entries')
    with op.batch_alter_table('lnk_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lnk_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_lnk_entries_case_id'))

    op.drop_table('lnk_entries')
    with op.batch_alter_table('jumplist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jumplist_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_jumplist_entries_case_id'))

    op.drop_table('jumplist_entries')
    with op.batch_alter_table('chainsaw_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chainsaw_alerts_timestamp'))
        batch_op.drop_index('ix_chainsaw_alerts_scan_level')
        batch_op.drop_index(batch_op.f('ix_chainsaw_alerts_scan_id'))
        batch_op.drop_index(batch_op.f('ix_chainsaw_alerts_rule_name'))
        batch_op.drop_index(batch_op.f('ix_chainsaw_alerts_level'))
        batch_op.drop_index('ix_chainsaw_alerts_case_ts')
        batch_op.drop_index('ix_chainsaw_alerts_case_level')
        batch_op.drop_index(batch_op.f('ix_chainsaw_alerts_case_id'))

    op.drop_table('chainsaw_alerts')
    with op.batch_alter_table('amcache_program_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amcache_program_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_amcache_program_entries_case_id'))

    op.drop_table('amcache_program_entries')
    with op.batch_alter_table('amcache_file_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amcache_file_entries_sha1'))
        batch_op.drop_index(batch_op.f('ix_amcache_file_entries_file_id'))
        batch_op.drop_index(batch_op.f('ix_amcache_file_entries_case_id'))

    op.drop_table('amcache_file_entries')
    with op.batch_alter_table('memory_plugin_results', schema=None) as batch_op:
        batch_op.drop_index('ix_mem_plugin_name')
        batch_op.drop_index('ix_mem_plugin_is_custom')
        batch_op.drop_index('ix_mem_plugin_dump_id')

    op.drop_table('memory_plugin_results')
    op.drop_table('incident_log_entries')
    with op.batch_alter_table('imported_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_files_collection_id'))
        batch_op.drop_index(batch_op.f('ix_imported_files_case_id'))

    op.drop_table('imported_files')
    with op.batch_alter_table('evtx_events', schema=None) as batch_op:
        batch_op.drop_index('ix_evtx_events_file_time')
        batch_op.drop_index('ix_evtx_events_file_level')
        batch_op.drop_index('ix_evtx_events_file_eid')
        batch_op.drop_index('ix_evtx_events_file_channel')
        batch_op.drop_index(batch_op.f('ix_evtx_events_event_id'))

    op.drop_table('evtx_events')
    op.drop_table('csv_artifact_files')
    with op.batch_alter_table('chainsaw_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chainsaw_scans_file_id'))
        batch_op.drop_index(batch_op.f('ix_chainsaw_scans_case_id'))

    op.drop_table('chainsaw_scans')
    op.drop_table('timeline_events')
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_report_versions_case')

    op.drop_table('report_versions')
    with op.batch_alter_table('memory_dumps', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_dump_case_id')

    op.drop_table('memory_dumps')
    op.drop_table('iocs')
    with op.batch_alter_table('imported_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_collections_session_id'))
        batch_op.drop_index(batch_op.f('ix_imported_collections_case_id'))

    op.drop_table('imported_collections')
    with op.batch_alter_table('evtx_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evtx_files_case_id'))

    op.drop_table('evtx_files')
    op.drop_table('evtx_case_selections')
    op.drop_table('evidences')
    op.drop_table('email_files')
    op.drop_table('chainsaw_case_selections')
    with op.batch_alter_table('case_ttps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_ttps_case_id'))

    op.drop_table('case_ttps')
    op.drop_table('case_playbooks')
    with op.batch_alter_table('binary_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_binary_files_case_id'))

    op.drop_table('binary_files')
    op.drop_table('attack_graphs')
    op.drop_table('assets')
    op.drop_table('client_documents')
    op.drop_table('cases')
    op.drop_table('clients')
    op.drop_table('vaults')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('report_doc_templates')
    op.drop_table('playbooks')
    op.drop_table('connector_configs')
    op.drop_table('client_doc_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_username')
        batch_op.drop_index('ix_audit_timestamp')
        batch_op.drop_index('ix_audit_resource_type')
        batch_op.drop_index('ix_audit_case_id')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
