"""attack graph snapshot

Revision ID: d7d1686462c6
Revises: 3c61ddde32ef
Create Date: 2026-08-28 13:48:53.081480+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7d1686462c6'
down_revision: Union[str, None] = '3c61ddde32ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack_graphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_png', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack_graphs', schema=None) as batch_op:
        batch_op.drop_column('snapshot_at')
        batch_op.drop_column('snapshot_png')

    # ### end Alembic commands ###
