/**
 * Icon registry — the single place `lucide-react` is imported.
 *
 * Two things live here, and they solve two different problems.
 *
 * `NAV_ICON` is the semantic layer: one concept, one icon, defined once. Before
 * this file existed, HardDrive stood for both *Logs* and *Disk Images*, FileText
 * for both *Vault* and *Case Templates*, and Shield for both *CTI Lookup* and
 * *Audit*. Nothing enforced otherwise, so the drift was invisible until someone
 * looked at the sidebar. Anything that needs to render a destination — the
 * sidebar, breadcrumbs, tabs, empty states, search results — reads it from here
 * and cannot disagree with anything else.
 *
 * The re-exports below cover the long tail of one-off icons. They keep their
 * lucide names; the point of routing them through this file is that the eslint
 * rule can then forbid `lucide-react` everywhere else, which is what makes the
 * convention enforceable rather than aspirational.
 *
 * Adding an icon: import it from lucide-react here and re-export it. If it
 * names a *concept* rather than a shape — a destination, a state, an action
 * that already exists elsewhere — check NAV_ICON and the existing exports first
 * so the same idea does not acquire a second picture.
 *
 * See docs/CONVENTIONS.md section 5.
 */
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignLeft,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  AtSign,
  BarChart3,
  Binary,
  BookOpen,
  BookmarkCheck,
  BookmarkPlus,
  Bug,
  Building2,
  Columns2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  Clipboard,
  ClipboardCheck,
  Clock,
  Code2,
  Columns3,
  Copy,
  Cpu,
  Crosshair,
  Database,
  Download,
  Edit2,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileDown,
  FileJson,
  FileOutput,
  FileQuestion,
  FileSearch,
  FileSpreadsheet,
  FileStack,
  FileText,
  FileType,
  Filter,
  Flag,
  FlaskConical,
  Folder,
  FolderInput,
  FolderOpen,
  FolderTree,
  GitBranch,
  Globe,
  GripVertical,
  HardDrive,
  Hash,
  HelpCircle,
  History,
  Image,
  ImageDown,
  ImageIcon,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link2,
  Link2Off,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  Minus,
  Monitor,
  Palette,
  Network,
  Package,
  Paperclip,
  Pencil,
  Play,
  Plug,
  Plus,
  Radar,
  Radio,
  RefreshCw,
  RotateCcw,
  Save,
  ScanSearch,
  ScreenShare,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Skull,
  SlidersHorizontal,
  Sparkles,
  Spline,
  SquareDashed,
  Star,
  StickyNote,
  Swords,
  Table2,
  TableProperties,
  Tag,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wand2,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react'

export type { LucideIcon }

/**
 * Destination -> icon. Keyed by route so a caller cannot pick the wrong entry
 * for a page it is already routing to.
 */
export const NAV_ICON: Record<string, LucideIcon> = {
  '/':                      LayoutDashboard,
  '/cases':                 FolderOpen,

  '/artifacts/explorer':    Table2,
  '/artifacts/email':       Mail,
  '/artifacts/filesystem':  ScrollText,     // Logs — was HardDrive, shared with Disk Images
  '/artifacts/pcap':        Network,
  '/artifacts/images':      HardDrive,      // Disk Images — keeps the drive
  '/artifacts/registry':    FolderTree,     // Registry Explorer — a tree of keys
  '/artifacts/rdp-cache':   ScreenShare,    // RDP Cache — a remote screen, not a local one
  '/artifacts/memory':      Cpu,
  '/artifacts/binary':      Binary,
  '/artifacts/cti':         Radar,          // CTI Lookup — was Shield, shared with Audit

  '/knowledge':             BookOpen,       // Vault — was FileText, shared with Case Templates

  '/config/clients':        Building2,
  '/templates':             FileText,       // Case Templates — keeps FileText
  '/report-templates':      FileOutput,
  '/playbooks':             GitBranch,
  '/config/chainsaw-rules': Swords,
  '/config/connectors':     Plug,
  '/config/vaults':         Archive,
  '/users':                 Users,
  '/audit':                 ShieldCheck,
  '/account':               User,          // the signed-in user's own account
  '/design':                Palette,      // design system gallery    // Audit — was Shield, shared with CTI Lookup
}

export {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignLeft,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  AtSign,
  BarChart3,
  Binary,
  BookOpen,
  BookmarkCheck,
  BookmarkPlus,
  Bug,
  Building2,
  Columns2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  Clipboard,
  ClipboardCheck,
  Clock,
  Code2,
  Columns3,
  Copy,
  Cpu,
  Crosshair,
  Database,
  Download,
  Edit2,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileDown,
  FileJson,
  FileOutput,
  FileQuestion,
  FileSearch,
  FileSpreadsheet,
  FileStack,
  FileText,
  FileType,
  Filter,
  Flag,
  FlaskConical,
  Folder,
  FolderInput,
  FolderOpen,
  FolderTree,
  GitBranch,
  Globe,
  GripVertical,
  HardDrive,
  Hash,
  HelpCircle,
  History,
  Image,
  ImageDown,
  ImageIcon,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link2,
  Link2Off,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  Minus,
  Monitor,
  Palette,
  Network,
  Package,
  Paperclip,
  Pencil,
  Play,
  Plug,
  Plus,
  Radar,
  Radio,
  RefreshCw,
  RotateCcw,
  Save,
  ScanSearch,
  ScreenShare,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Skull,
  SlidersHorizontal,
  Sparkles,
  Spline,
  SquareDashed,
  Star,
  StickyNote,
  Swords,
  Table2,
  TableProperties,
  Tag,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wand2,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
}
